CREATE TABLE CDS(

ID INTEGER PRIMARY KEY,
TASSA_ISCR INTEGER,
MAX_SQUADRE INTEGER

);


CREATE TABLE EDIZIONE_CDS(

ID_EDIZIONE INTEGER PRIMARY KEY,
CDS INTEGER,
ANNO INTEGER,

INDEX idx_edcds(CDS), 
FOREIGN KEY (CDS) REFERENCES CDS(ID)

);


CREATE TABLE GARE(

ID_GARE INTEGER PRIMARY KEY,
ED_CDS INTEGER,
ORARIO VARCHAR(255),
SPECIALITA VARCHAR(255),

INDEX idx_edcds2(ED_CDS),
FOREIGN KEY (ED_CDS) REFERENCES EDIZIONE_CDS(ID_EDIZIONE)


);


CREATE TABLE SQUADRA
(

ID INTEGER AUTO_INCREMENT PRIMARY KEY,
Nome_Squadra VARCHAR(255),
Password VARCHAR(255),
Num_Atleti INTEGER,
ED_CDS INTEGER,

UNIQUE KEY `Nome_Squadra` (`Nome_Squadra`),
INDEX idx_edcds3(ED_CDS),
FOREIGN KEY (ED_CDS) REFERENCES EDIZIONE_CDS(ID_EDIZIONE)

);


CREATE TABLE ATLETA 
(

ID INTEGER PRIMARY KEY,
Nome VARCHAR(255),
Cognome VARCHAR(255),
Eta INTEGER,
Data DATE NOT NULL,
Squadra INTEGER,

INDEX idx_sq(Squadra),
FOREIGN KEY (Squadra) REFERENCES SQUADRA(ID)

);


CREATE TABLE CLASSIFICA_PASSATA(

SQUADRA INTEGER,
GIORNO DATE,
PUNTEGGIO_SQUADRA INTEGER,

INDEX idx_squadra(SQUADRA),
FOREIGN KEY (Squadra) REFERENCES SQUADRA(ID),

PRIMARY KEY(SQUADRA, GIORNO)


);


CREATE TABLE CLASSIFICA_CORRENTE(

SQUADRA INTEGER,
GIORNO DATE,
PUNTEGGIO_SQUADRA INTEGER,

INDEX idx_squadra(SQUADRA),
FOREIGN KEY (Squadra) REFERENCES SQUADRA(ID),

PRIMARY KEY(SQUADRA, GIORNO)


);

CREATE TABLE TITOLO(

RICONOSCIMENTO VARCHAR(255) PRIMARY KEY,
PREMIO INTEGER
);

CREATE TABLE NEWS(
id integer primary key auto_increment,
titolo varchar(255),
url varchar(255),
descrizione varchar(255)
);

CREATE TABLE COMMENTI(
id integer primary key auto_increment,
cod_news integer,
commento varchar(255),
nome_squadra varchar(255),
squadra integer,
INDEX idx_squadra2(squadra),
FOREIGN KEY (Squadra) REFERENCES SQUADRA(ID)
);

CREATE TABLE SPECIALITA(
id integer primary key auto_increment,
titolo varchar(255),
url varchar(255),
descrizione varchar(255)
);

